#!/usr/bin/env python3
"""
build_keyman_wordlist.py - generate the Keyman lexical model wordlist.

This is the answer to "why is there no swipe on iOS". iOS gives third-party
keyboards no gesture-typing API at all, and Keyman does not implement swipe, so
the `.dict` we built for HeliBoard is dead weight there. What Keyman DOES give
is a lexical model: word prediction and autocorrect in a bar above the keyboard.
That is the half of swipe's value which is reachable on iOS - you type
`medzuslovjansk` and get the rest offered.

Same source as the Android dictionary, but TRIMMED - see MIN_FREQ below for why
iOS cannot take the full 248k. Forms, not lemmas either way: prediction is
worthless if it only knows `slovo` when you are typing `slovami`.

Input is the AOSP `.combined` wordlist (`word=X,f=N` lines, f is a 1..255
log-ish scale). Keyman wants a plain `word<TAB>count` TSV; f is carried across
unchanged because only the ORDERING matters to the trie, not the absolute
numbers.

USAGE
    python3 build_keyman_wordlist.py
    kmc build keyman/radoslove.isv.wordlist/radoslove.isv.wordlist.kpj
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "keyman", "radoslove.isv.wordlist", "source",
                   "wordlist.tsv")

# The wordlist lives in the repo so the model can be rebuilt without the vault;
# the vault copy is the fallback for a fresh checkout that predates that.
SOURCES = [
    os.path.join(HERE, "dictionary", "main_isv.combined"),
    "/Users/radoslawkaczmarczyk/Projects/vault_002/Projects/INTERSLOVE/"
    "keyboards/upstream_prep/helium314/wordlists/main_isv.combined",
]

LINE = re.compile(r"\s*word=(\S+?),f=(\d+)")

# Frequency floor. The full 248k list builds a 33 MB trie, and an iOS keyboard
# EXTENSION - not the app, the extension - runs under a hard memory cap; a trie
# that size expands several times over once parsed and takes the keyboard down
# with it. Android has no such cap and keeps using the full list.
#
# f is a genuine corpus frequency - the top of the list is `i da dlja ne iz s
# ja do čto`, exactly the function words you would expect. It is NOT constant
# across a paradigm (`pisa*` ranges 115..161), so the floor also trims the rarer
# forms of common words, not just rare words whole. For a prediction dictionary
# that is the correct behaviour: a form nobody types is a suggestion nobody
# wants.
#
# 100 keeps ~39.6k forms / ~5 MB. Raise for a smaller model, lower for more
# vocabulary.
MIN_FREQ = 100

# The corpus behind f barely knows the words this project is ABOUT
# (`medžuslovjansky` and `slovjansky` sit at f=26, `tipkovnica` at 99), so a
# plain floor drops precisely the vocabulary the owner types most. These stay in
# regardless of frequency; it costs a few hundred forms.
KEEP_PREFIXES = ("medžuslovjan", "slovjansk", "tipkovnic", "klaviatur",
                 "slovnik", "jezyk")

# HOUSE_STYLE §1: the extended letters are not written, so they must not be
# predicted either. A suggestion bar is a spelling authority whether it means
# to be one or not.
BANNED = set("ųėȯŕťďľđęćńśźåÅŲĖȮŔŤĎĽĐĘĆŃŚŹ")


def main():
    src = next((p for p in SOURCES if os.path.exists(p)), None)
    if not src:
        sys.exit("no wordlist found; looked in:\n  " + "\n  ".join(SOURCES))

    kept, banned, rare, total, rescued = [], 0, 0, 0, 0
    for line in open(src, encoding="utf-8"):
        m = LINE.match(line)
        if not m:
            continue
        total += 1
        word, freq = m.group(1), int(m.group(2))
        if set(word) & BANNED:
            banned += 1
            continue
        if freq < MIN_FREQ:
            if word.lower().startswith(KEEP_PREFIXES):
                rescued += 1
            else:
                rare += 1
                continue
        kept.append((word, freq))

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# Medžuslovjansky - inflected forms, standard orthography.\n")
        f.write("# GENERATED by build_keyman_wordlist.py - do not edit.\n")
        f.write("# source: %s (f >= %d)\n" % (os.path.basename(src), MIN_FREQ))
        for word, freq in kept:
            f.write("%s\t%d\n" % (word, freq))

    print("source : %s" % src)
    print("total  : %d forms" % total)
    print("kept   : %d forms (%.1f%%)" % (len(kept), 100.0 * len(kept) / total))
    print("cut    : %d below f=%d" % (rare, MIN_FREQ))
    print("rescued: %d domain forms kept below the floor" % rescued)
    print("banned : %d (extended orthography, HOUSE_STYLE §1)" % banned)
    print("wrote  : %s" % OUT)


if __name__ == "__main__":
    main()
