#!/usr/bin/env python3
"""
build_keyman.py - generate the Keyman keyboard (keyman/isv_latin/source/).

This is the iOS/iPadOS track. iOS has no layout-file format at all: a third-party
keyboard there is a full app. Keyman is the way around that - it is a free App Store
app that loads .kmp keyboard packages, so we ship a package instead of an app.
The same .kmp also installs on Android, Windows, macOS and Linux.

Two artefacts come out of the one table below:

  * isv_latin.kmn                  - the rules. RALT (AltGr) mirrors the Windows
                                     layout key-for-key, so desktop behaviour is
                                     identical to windows/src/KBDMSSTD.klc.
  * isv_latin.keyman-touch-layout  - the phone/tablet layout. There is no AltGr on
                                     a touchscreen, so the same letters sit on
                                     LONGPRESS of their base letter (hold c -> c).

Standard orthography ONLY (HOUSE_STYLE.md §1), matching the Windows .klc and the
macOS .keylayout: c-caron, s-caron, z-caron, e-caron plus the punctuation our MS
texts actually use. The extended block is deliberately absent.

GOTCHA - touch subkeys cannot reach AltGr. The valid `layer` values in a touch
layout are only shift/ctrl/alt/ctrlshift/altshift/ctrlalt/ctrlaltshift; `rightalt`
is not one of them. So the longpress keys are touch-only T_* keys with their own
rules, NOT a re-use of the RALT rules. Both sets are emitted from LETTERS below,
which is what keeps desktop and touch in agreement.

USAGE
    python3 build_keyman.py
    kmc build keyman/isv_latin/isv_latin.kpj
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "keyman", "isv_latin", "source")

KEYBOARD_NAME = "Medžuslovjansky (latinica)"
COPYRIGHT = "© Radoslove"
KEYBOARD_VERSION = "1.2"

# --- the canonical table -------------------------------------------------
# base key -> (lowercase, uppercase, T_ key stem)
# The base key is BOTH the AltGr key on desktop and the longpress host on touch;
# for these four they happen to coincide, which is why the mnemonic works.
LETTERS = [
    ("K_C", "č", "Č", "CCARON"),
    ("K_S", "š", "Š", "SCARON"),
    ("K_Z", "ž", "Ž", "ZCARON"),
    ("K_E", "ě", "Ě", "ECARON"),
]

# desktop-only: AltGr punctuation, same cells as the Windows layout
PUNCT = [
    ("K_COLON", "„", "“"),   # ;  -> low / high double quote
    ("K_QUOTE", "’", "”"),   # '  -> right single / right double quote
    ("K_HYPHEN", "–", "—"),  # -  -> en dash / em dash
]

# touch-only punctuation keys (longpress), name -> character
TOUCH_PUNCT = [
    ("QUOTLOW", "„"),
    ("QUOTHIGH", "”"),
    ("ENDASH", "–"),
    ("EMDASH", "—"),
]


# --- .kmn ----------------------------------------------------------------
def build_kmn():
    L = []
    add = L.append
    add("c isv_latin - Interslavic (Latin), standard orthography")
    add("c GENERATED by build_keyman.py - do not edit by hand")
    add("")
    add("store(&NAME) '%s'" % KEYBOARD_NAME)
    add("store(&COPYRIGHT) '%s'" % COPYRIGHT)
    add("store(&VERSION) '10.0'")
    add("store(&KEYBOARDVERSION) '%s'" % KEYBOARD_VERSION)
    add("store(&TARGETS) 'windows macosx linux web iphone ipad "
        "androidphone androidtablet mobile desktop tablet'")
    add("store(&VISUALKEYBOARD) 'isv_latin.kvks'")
    add("store(&LAYOUTFILE) 'isv_latin.keyman-touch-layout'")
    add("")
    add("begin Unicode > use(main)")
    add("")
    add("group(main) using keys")
    add("")
    add("c --- desktop: AltGr, mirroring windows/src/KBDMSSTD.klc ---")
    for key, lo, up, _stem in LETTERS:
        add("+ [RALT %s] > '%s'" % (key, lo))
        add("+ [SHIFT RALT %s] > '%s'" % (key, up))
    add("")
    for key, lo, up in PUNCT:
        add("+ [RALT %s] > '%s'" % (key, lo))
        add("+ [SHIFT RALT %s] > '%s'" % (key, up))
    add("")
    add("c --- touch: longpress keys. Subkeys cannot reach RALT, so these")
    add("c     touch-only T_ keys carry the same letters explicitly.")
    add("c")
    add("c     GOTCHA, paid for on a device twice: a subkey on the SHIFT layer")
    add("c     fires with the shift modifier held, so a bare '+ [T_X]' rule does")
    add("c     NOT match there and the key silently emits nothing. The fix is the")
    add("c     [SHIFT ...] rules below. Do NOT also pin the subkey to")
    add("c     layer 'default' in the touch layout - that breaks id resolution")
    add("c     and the subkey falls back to its parent letter (C instead of Č).")
    for _key, lo, up, stem in LETTERS:
        add("+ [T_%s] > '%s'" % (stem, lo))
        add("+ [SHIFT T_%s] > '%s'" % (stem, lo))
        add("+ [T_%s_UC] > '%s'" % (stem, up))
        add("+ [SHIFT T_%s_UC] > '%s'" % (stem, up))
    add("")
    for stem, ch in TOUCH_PUNCT:
        add("+ [T_%s] > '%s'" % (stem, ch))
        add("+ [SHIFT T_%s] > '%s'" % (stem, ch))
    add("")
    return "\n".join(L) + "\n"


# --- touch layout --------------------------------------------------------
ROW1 = "qwertyuiop"
ROW2 = "asdfghjkl"
ROW3 = "zxcvbnm"

# longpress hosts: base letter -> list of (text, T_ id)
def subkeys(upper):
    out = {}
    for _key, lo, up, stem in LETTERS:
        host = lo[0] if not upper else up[0]
        # host letter is the plain ascii base: c/s/z/e
        base = {"č": "c", "š": "s", "ž": "z", "ě": "e"}[lo]
        host = base.upper() if upper else base
        out[host] = [{"text": up if upper else lo,
                      "id": "T_%s%s" % (stem, "_UC" if upper else "")}]
    return out


def key(char, upper=False, sk_map=None):
    k = {"id": "K_" + char.upper(), "text": char}
    if sk_map and char in sk_map:
        k["sk"] = sk_map[char]
    return k


def period_key(upper):
    """The . key keeps its stock punctuation popup, plus the MS quotes."""
    sk = [
        {"text": ",", "id": "K_COMMA"},
        {"text": "!", "id": "K_1", "layer": "shift"},
        {"text": "?", "id": "K_SLASH", "layer": "shift"},
        {"text": "„", "id": "T_QUOTLOW"},
        {"text": "”", "id": "T_QUOTHIGH"},
        {"text": "'", "id": "K_QUOTE"},
        {"text": "\"", "id": "K_QUOTE", "layer": "shift"},
        {"text": ":", "id": "K_COLON", "layer": "shift"},
        {"text": ";", "id": "K_COLON"},
    ]
    return {"id": "K_PERIOD", "text": ".", "sk": sk}


def letter_layer(layer_id, upper):
    sk_map = subkeys(upper)
    cases = (lambda s: s.upper()) if upper else (lambda s: s)
    r1 = [key(cases(c), upper, sk_map) for c in ROW1]
    r2 = [key(cases(c), upper, sk_map) for c in ROW2]
    r2[0]["pad"] = "50"
    r2.append({"text": "", "width": "10", "sp": "10"})
    r3 = [{"id": "K_SHIFT", "text": "*Shift*", "sp": "1",
           "nextlayer": "default" if upper else "shift"}]
    r3 += [key(cases(c), upper, sk_map) for c in ROW3]
    r3.append(period_key(upper))
    r3.append({"id": "K_BKSP", "text": "*BkSp*", "width": "100", "sp": "1"})
    r4 = [
        {"id": "K_NUMLOCK", "text": "*123*", "width": "150", "sp": "1",
         "nextlayer": "numeric"},
        {"id": "K_LOPT", "text": "*Menu*", "width": "120", "sp": "1"},
        {"id": "K_SPACE", "text": "", "width": "610", "sp": "0"},
        {"id": "K_ENTER", "text": "*Enter*", "width": "150", "sp": "1"},
    ]
    return {"id": layer_id,
            "row": [{"id": 1, "key": r1}, {"id": 2, "key": r2},
                    {"id": 3, "key": r3}, {"id": 4, "key": r4}]}


def numeric_layer():
    digits = [{"id": "K_" + d, "text": d} for d in "1234567890"]
    sym = [("K_4", "$"), ("K_2", "@"), ("K_3", "#"), ("K_5", "%"),
           ("K_7", "&"), ("K_HYPHEN", "_"), ("K_EQUAL", "="),
           ("K_BKSLASH", "|"), ("K_BKSLASH", "\\")]
    r2 = [{"id": i, "text": t} for i, t in sym]
    r2.append({"text": "", "width": "10", "sp": "10"})
    r3 = [
        {"id": "K_LBRKT", "text": "["},
        {"id": "K_9", "text": "("},
        {"id": "K_0", "text": ")"},
        {"id": "K_RBRKT", "text": "]"},
        {"id": "K_EQUAL", "text": "+"},
        {"id": "K_HYPHEN", "text": "-",
         "sk": [{"text": "–", "id": "T_ENDASH"},
                {"text": "—", "id": "T_EMDASH"}]},
        {"id": "K_8", "text": "*"},
        {"id": "K_SLASH", "text": "/"},
        {"id": "K_BKSP", "text": "*BkSp*", "width": "100", "sp": "1"},
    ]
    r4 = [
        {"id": "K_LOWER", "text": "*abc*", "width": "150", "sp": "1",
         "nextlayer": "default"},
        {"id": "K_LOPT", "text": "*Menu*", "width": "120", "sp": "1"},
        {"id": "K_SPACE", "text": "", "width": "610", "sp": "0"},
        {"id": "K_ENTER", "text": "*Enter*", "width": "150", "sp": "1"},
    ]
    return {"id": "numeric",
            "row": [{"id": 1, "key": digits}, {"id": 2, "key": r2},
                    {"id": 3, "key": r3}, {"id": 4, "key": r4}]}


def build_touch_layout():
    layers = [letter_layer("default", False),
              letter_layer("shift", True),
              numeric_layer()]
    form = {"font": "Tahoma", "layer": layers}
    # iPad reports as tablet; without this form Keyman falls back to the phone
    # layout scaled up. Same rows - the point is that the popups exist there too.
    return {"phone": form, "tablet": json.loads(json.dumps(form))}


def main():
    os.makedirs(SRC, exist_ok=True)

    kmn_path = os.path.join(SRC, "isv_latin.kmn")
    with open(kmn_path, "w", encoding="utf-8") as f:
        f.write(build_kmn())
    print("wrote %s" % kmn_path)

    tl_path = os.path.join(SRC, "isv_latin.keyman-touch-layout")
    with open(tl_path, "w", encoding="utf-8") as f:
        json.dump(build_touch_layout(), f, ensure_ascii=False, indent=2)
        f.write("\n")
    print("wrote %s" % tl_path)


if __name__ == "__main__":
    main()
